### ISSUE TITLE
[BUG]: Autopilot takes away your control.

### ISSUE THREAD

**Issue by tupoy-ya** [YimMenu-Lua/Samurais-Scripts#13] opened 2024-08-22 21:04 UTC
### Describe The Bug

If you enter, then exit a helicopter and start autopilot - your ped will enter the helicopter but will not return you control when you try to fly yourself, the stop button also does not appear.
A work around is to enable auto pilot again this will create the stop button.

### Steps To Reproduce

1. Spawn and enter a buzzard.
2. Exit the buzzard.
3. Go and enable the auto pilot.

### Log

# 🪵
To lazy to get clean logs, and I don't think there are any logs for this.

### Additional context

Used TupoyeMenu, was able to reproduce consistently.
Did not restart the game.
Used " Random " autopilot.

**Comment by xesdoog** [comment] 2024-08-22 21:25
This was caused by me trying to give the user the freedom to use the main vehicle features without having to be sitting in a vehicle. This particular issue can be fixed by only showing or making the auto-pilot available if you're actively flying an aircraft. We already have the `isDriving()` check so just using that would be enough. What do you think?
Also thank you for that last PR especially getting rid of natives that were called outside the fiber pool. I've changed the `isOnline()` check to use memory instead just like the game version since that function often gets called outside too.

**Comment by tupoy-ya** [comment] 2024-08-22 21:30
> What do you think?

Yes

> I've changed the isOnline() check to use memory instead just like the game version since that function often gets called outside too.

Why not just use `network.is_session_started()` instead of `Game.isOnline()`?

**Comment by xesdoog** [comment] 2024-08-22 21:35
> Why not just use `network.is_session_started()` instead of `Game.isOnline()`?

omg I'm such an idiot 😭

**Closed** 2024-08-22 22:31 UTC
Labels: bug
